spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mohamedYoussfi/bank-account-config-repo
  discovery:
    enabled: true

server:
  port: 9999

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${DISCOVERY_SERVICE_URL:http://localhost:8761/eureka}

management:
  endpoints:
    web:
      exposure:
        include: "*"
